### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by mwaldron104** [Illumina/isaac2#1] opened 2015-07-15 19:16 UTC
I am getting the following error when running the make command after running configure:
$ make
Scanning dependencies of target iSAAC_OPT
[  0%] Built target iSAAC_OPT
Scanning dependencies of target isaac_bgzf
[  1%] Building CXX object c++/lib/bgzf/CMakeFiles/isaac_bgzf.dir/BgzfReader.cpp.o
Linking CXX static library libisaac_bgzf.a
[  1%] Built target isaac_bgzf
Scanning dependencies of target isaac_common
[  2%] Building CXX object c++/lib/common/CMakeFiles/isaac_common.dir/Debug.cpp.o
[  3%] Building CXX object c++/lib/common/CMakeFiles/isaac_common.dir/Exceptions.cpp.o
[  4%] Building CXX object c++/lib/common/CMakeFiles/isaac_common.dir/FileSystem.cpp.o
[  4%] Building CXX object c++/lib/common/CMakeFiles/isaac_common.dir/MD5Sum.cpp.o
[  5%] Building CXX object c++/lib/common/CMakeFiles/isaac_common.dir/Process.cpp.o
[  6%] Building CXX object c++/lib/common/CMakeFiles/isaac_common.dir/Program.cpp.o
[  7%] Building CXX object c++/lib/common/CMakeFiles/isaac_common.dir/SystemCompatibility.cpp.o
/nas02/apps/isaac2-15.07.14/src/isaac2/src/c++/lib/common/SystemCompatibility.cpp: In function 'int isaac::common::linuxFallocate(int, std::size_t, std::size_t)':
/nas02/apps/isaac2-15.07.14/src/isaac2/src/c++/lib/common/SystemCompatibility.cpp:162:58: error: 'fallocate' was not declared in this scope
     return fallocate(fd, FALLOC_FL_KEEP_SIZE, offset, len);
                                                          ^
/nas02/apps/isaac2-15.07.14/src/isaac2/src/c++/lib/common/SystemCompatibility.cpp:163:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[2]: **\* [c++/lib/common/CMakeFiles/isaac_common.dir/SystemCompatibility.cpp.o] Error 1
make[1]: **\* [c++/lib/common/CMakeFiles/isaac_common.dir/all] Error 2
make: **\* [all] Error 2

**Comment by rpetrovski** [comment] 2015-07-15 19:58
Which operating system and OS version are you trying to use?

**Comment by mwaldron104** [comment] 2015-07-15 20:01
The OS is RedHat Enterprise Linux 5.11.

I am using GCC-4.8.1 compiler.

Mike Waldron
Systems Specialist
ITS - Research Computing Center
University of North Carolina at Chapel Hill

**Comment by rpetrovski** [comment] 2015-07-15 20:59
It will take some time before I can try it on rhel box. As a quick check, can you please put
#include <fcntl.h>
between lines 154 and 155 of SystemCompatibility.cpp and tell me if it helped.

Roman.

**Comment by mwaldron104** [comment] 2015-07-16 12:16
I added #include between lines 154 and 155 such that it now looks like:

Before:
153 #ifdef HAVE_LINUX_FALLOC_H
154 #include <linux/falloc.h>
155 #else // #ifdef HAVE_LINUX_FALLOC_H
156 #error The header <linux/falloc.h> is required.
157 #endif // #ifdef HAVE_LINUX_FALLOC_H

After:
153 #ifdef HAVE_LINUX_FALLOC_H
154 #include <linux/falloc.h>
155 #include
156 #else // #ifdef HAVE_LINUX_FALLOC_H
157 #error The header <linux/falloc.h> is required.
158 #endif // #ifdef HAVE_LINUX_FALLOC_H

But I get the error:

[  2%] Building CXX object c++/lib/common/CMakeFiles/isaac_common.dir/SystemCompatibility.cpp.o
/nas02/apps/isaac2-15.07.14/src/isaac2/src/c++/lib/common/SystemCompatibility.cpp:155:9: error: #include expects "FILENAME" or <FILENAME>
 #include
         ^
/nas02/apps/isaac2-15.07.14/src/isaac2/src/c++/lib/common/SystemCompatibility.cpp: In function 'int isaac::common::linuxFallocate(int, std::size_t, std::size_t)':
/nas02/apps/isaac2-15.07.14/src/isaac2/src/c++/lib/common/SystemCompatibility.cpp:163:58: error: 'fallocate' was not declared in this scope
     return fallocate(fd, FALLOC_FL_KEEP_SIZE, offset, len);
                                                          ^
/nas02/apps/isaac2-15.07.14/src/isaac2/src/c++/lib/common/SystemCompatibility.cpp:164:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[2]: **\* [c++/lib/common/CMakeFiles/isaac_common.dir/SystemCompatibility.cpp.o] Error 1
make[1]: **\* [c++/lib/common/CMakeFiles/isaac_common.dir/all] Error 2
make: **\* [all] Error 2

Mike Waldron
Systems Specialist
ITS - Research Computing Center
University of North Carolina at Chapel Hill

**Comment by rpetrovski** [comment] 2015-07-16 12:20
Yeah, I meant #include <fcntl.h> but the github lost the file bit.

I've got the problem reproduced on CentOS 5.4. Turns out fallocate is not available in CentOS (and I guess RHEL) 5. I'm going to commit code that uses posix_fallocate instead shortly.

Roman.

**Comment by rpetrovski** [comment] 2015-07-16 12:43
Just pushed the fix. Please let me know if you have any further issues.

Roman.

**Closed as completed by rpetrovski** 2015-07-16 12:43 UTC

**Comment by mwaldron104** [comment] 2015-07-16 13:49
Successfully compiled. Thanks for the quick fix.

Mike Waldron
Systems Specialist
ITS - Research Computing Center
University of North Carolina at Chapel Hill

**Comment by kvshams** [comment] 2015-12-15 17:57
I am using Red Hat 4.4.5-6 version (Linux version 2.6.32-220.el6.x86_64)
I am getting the similar compiling error with the version (iSAAC-02.15.10.21)

make[2]: **\* [c++/lib/bgzf/CMakeFiles/isaac_bgzf.dir/BgzfReader.cpp.o] Error 1
make[1]: **\* [c++/lib/bgzf/CMakeFiles/isaac_bgzf.dir/all] Error 2
make: **\* [all] Error 2

**Comment by rpetrovski** [comment] 2015-12-15 18:53
This is a different error. Please create a separate ticket and post more details for the compilation failure.

Roman.

**Comment by kvshams** [comment] 2015-12-18 13:25
I have already made a new ticket but I did not get any responds yet

Thanks
Shams
